apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: petclinic-flux-kustomization
  namespace: petclinic
spec:
  interval: 1m0s
  path: Kubernetes
  prune: false
  # serviceAccountName: default
  sourceRef:
    kind: GitRepository
    name: spring-petclinic-repo
  targetNamespace: petclinic
