apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  namespace: petclinic
  name: spring-petclinic-repo
spec:
  interval: 5m0s
  secretRef:
    name: spring-petclinic-deploy-key
  ref:
    branch: main
  url: ssh://git@github.com/alaric11/spring-petclinic.git
