# db-service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: petclinic
  name: petclinic
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
    - name: "http"
      protocol: TCP
      port: 8080
